language: python

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - python -m pip install --upgrade pip
  - python --version
  - pip --version