image:
  # - Visual Studio 2015
  - Ubuntu
  - macOS

environment:
  matrix:
  - BUILDFOR: python
  # - BUILDFOR: c++
  # - BUILDFOR: lua
  # - BUILDFOR: php

install:
# - cmd: 'set PATH=%PYTHON%;%PYTHON%\\scripts;%PATH%'
# - cmd: 'set VS90COMNTOOLS=%VS140COMNTOOLS%'
# - cmd: 'set VS100COMNTOOLS=%VS140COMNTOOLS%'
# - cmd: 'echo %VS90COMNTOOLS%'

# - cmd: 'cd "c:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\"'
# - cmd: 'ren "Visual C++ for Python" "Visual C++ for Python Do Not Use"'

# - cmd: 'cd "C:\Program Files (x86)\"'
# - cmd: 'ren "Microsoft Visual Studio 9.0" "Microsoft Visual Studio 9.0 Do Not Use"'
# - cmd: 'ren "Microsoft Visual Studio 10.0" "Microsoft Visual Studio 10.0 Do Not Use"'

# - echo %APPVEYOR_REPO_BRANCH%

# - cmd: 'IF "%PYTHON_ARCH%"=="64" (call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64) ELSE ( call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86)'
# - cmd: 'cd %APPVEYOR_BUILD_FOLDER%'  #回到原来目录里

# 环境设置完毕后，交由python来处理
- cmd: 'C:/Python37/python.exe  main.py'
- sh: ls
- sh: ls $HOME/venv3.7/bin
- sh: '$HOME/venv3.7/bin/python mian.py'

build: off
test: off

