image:
  - Visual Studio 2015
  - Ubuntu
  - macOS

environment:
  matrix:
  - BUILDFOR: python
  # - BUILDFOR: c++
  # - BUILDFOR: lua
  # - BUILDFOR: php

install:
# 环境设置完毕后，交由python来处理
  - ps:  $env:CI_WINDOWS | C:/Python37/python.exe  work.py

 
  - sh: $HOME/venv3.7/bin/python work.py

build: off
test: off

