image:
  - Visual Studio 2015
  - Ubuntu
  - macOS

environment:
  matrix:
  - BUILDFOR: python
  # - BUILDFOR: c++
  # - BUILDFOR: lua
  # - BUILDFOR: php

install:
  # 环境设置完毕后，交由python来处理
  # python3.9
  - cmd: choco install -y python3 --version 3.9.7 --force --ignore-dependencies  --side-by-side --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\Python39-x64'"
  - cmd: choco install -y python3 --version 3.9.7  --force --ignore-dependencies --x86 --side-by-side --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\Python39'"
  # python3.10
  - cmd: choco install -y python3 --version 3.10.5 --force --ignore-dependencies --side-by-side --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\Python310-x64'"
  - cmd: choco install -y python3 --version 3.10.5 --force --ignore-dependencies --x86 --side-by-side --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\Python310'"
    # python3.11
  - cmd: choco install -y python3 --version 3.11.0 --force --ignore-dependencies --side-by-side --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\Python311-x64'"
  - cmd: choco install -y python3 --version 3.11.0 --force --ignore-dependencies --x86 --side-by-side --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\Python311'"

  # python3.12
  - cmd: choco install -y python3 --version 3.12.0 --force --ignore-dependencies --side-by-side --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\Python312-x64'"
  - cmd: choco install -y python3 --version 3.12.0 --force --ignore-dependencies --x86 --side-by-side --installarguments "'/quiet  InstallAllUsers=1 TargetDir=c:\Python312'"




  - cmd: C:/Python37/python.exe  work.py
  - sh: $HOME/venv3.7/bin/python work.py

build: off
test: off

